=== Fedesky25/finite-potential-barrier/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "description": "Detail of a transmission plot",
    "type": "object",
    "properties": {
        "energies": {
            "type": "object",
            "description": "Range values of energies [eV] for which compute the transmission",
            "properties": {
                "min": {
                    "type": "number",
                    "minimum": 0
                },
                "max": {
                    "type": "number",
                    "exclusiveMinimum": 0
                },
                "steps": {
                    "type": "number",
                    "minimum": 10
                }
            },
            "required": ["max"]
        },
        "potential": {"$ref": "#/definitions/potential"},
        "length": {"$ref": "#/definitions/length"},
        "mass": {"$ref": "#/definitions/mass"},
        "plots": {
            "type": "array",
            "minItems": 1,
            "description": "Set of plot information",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                        "minLength": 1,
                        "description": "Plot name"
                    },
                    "potential": {"$ref": "#/definitions/potential"},
                    "length": {"$ref": "#/definitions/length"},
                    "mass": {"$ref": "#/definitions/mass"}
                },
                "required": ["name"],
                "additionalProperties": false
            }
        }
    },
    "additionalProperties": false,
    "required": ["energies", "plots"],
    "allOf": [
        {
            "anyOf": [
                { "required": ["potential"] },
                { "properties": { "plots": { "items": { "required": ["potential"] } } }
                }
            ]
        },
        {
            "anyOf": [
                { "required": ["length"] },
                { "properties": { "plots": { "items": { "required": ["length"] } } }
                }
            ]
        }
    ],
    "definitions": {
        "length": {
            "type": "number",
            "exclusiveMinimum": 0,
            "description": "Barrier length [Angstrom]"
        },
        "potential": {
            "type": "number",
            "exclusiveMinimum": 0,
            "description": "Barrier potential [eV]"
        },
        "mass": {
            "description": "Particle mass [electron masses]",
            "anyOf": [
                {
                    "type": "number",
                    "exclusiveMinimum": 0
                },
                {
                    "type": "string",
                    "enum": [
                        "v_e", "electron neutrino",
                        "v_m", "muon neutrino",
                        "e", "electron",
                        "u", "quark up",
                        "d", "quark down",
                        "v_t", "tau neutrino",
                        "m", "muon",
                        "p", "proton"
                    ]
                }
            ]
        }
    }
}

=== Fedesky25/finite-potential-barrier/data/masses.json
{
    "energies": {
        "max": 15
    },
    "potential": 5,
    "length": 0.2,
    "plots": [
        {
            "name": "electron",
            "mass": "e"
        },
        {
            "name": "tau-neutrino",
            "mass": "v_t"
        },
        {
            "name": "muon",
            "mass": "m"
        },
        {
            "name": "proton",
            "mass": "p"
        }
    ]
}
